//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgencyWPF.ADOApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstateAgencyEntities : DbContext
    {
        public EstateAgencyEntities()
            : base("name=EstateAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<FlatBase> FlatBase { get; set; }
        public virtual DbSet<FlatType> FlatType { get; set; }
        public virtual DbSet<Heating> Heating { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<ImageFlat> ImageFlat { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<UserFlatBase> UserFlatBase { get; set; }
        public virtual DbSet<UserRequest> UserRequest { get; set; }
        public virtual DbSet<Flat> Flat { get; set; }
        public virtual DbSet<FlatInformation> FlatInformation { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
