//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgencyWPF.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flat()
        {
            this.FlatBase = new HashSet<FlatBase>();
            this.ImageFlat = new HashSet<ImageFlat>();
        }
    
        public int IdFlat { get; set; }
        public int Owner { get; set; }
        public int FlatInformation { get; set; }
        public int Address { get; set; }
    
        public virtual Address Address1 { get; set; }
        public virtual Owner Owner1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlatBase> FlatBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageFlat> ImageFlat { get; set; }
        public virtual FlatInformation FlatInformation1 { get; set; }
    }
}
