//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgencyWPF.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        public int IdFlat { get; set; }
        public int Owner { get; set; }
        public int CountRoom { get; set; }
        public decimal FloorSpace { get; set; }
        public int Floor { get; set; }
        public int SleepingRooms { get; set; }
        public int Bathrooms { get; set; }
        public bool Internet { get; set; }
        public bool TV { get; set; }
        public bool Available { get; set; }
    }
}
