//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgencyWPF.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFlatBase
    {
        public int IdUserFlatBase { get; set; }
        public int User { get; set; }
        public int FlatBase { get; set; }
    
        public virtual FlatBase FlatBase1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
